# SPDX-FileCopyrightText: Copyright (c) 2021 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-FileCopyrightText: Copyright (c) 2021 ETH Zurich, Nikita Rudin
# SPDX-FileCopyrightText: Copyright (c) 2024 Beijing RobotEra TECHNOLOGY CO.,LTD. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
#
# Asimov v1 stand/walk configuration. Derived from agibot_x1_train X1DHStandCfg.
# Phase 1 scope: 12-DOF lower body (upper body frozen as fixed joints in URDF).

from asimov_rl.envs.base.legged_robot_config import LeggedRobotCfg, LeggedRobotCfgPPO


class AsimovStandCfg(LeggedRobotCfg):
    """Configuration for Asimov v1 humanoid standing/walking task (legs only)."""

    class env(LeggedRobotCfg.env):
        # Observation stack: 66 historical frames feed the long-history CNN,
        # 5 short frames feed the state estimator, 3 critic frames feed the
        # privileged critic. Matches X1 layout because we run 12 active DOF.
        frame_stack = 66
        short_frame_stack = 5
        c_frame_stack = 3
        num_single_obs = 47          # 5 cmd + 12 q + 12 dq + 12 a + 3 omega + 3 euler
        num_observations = int(frame_stack * num_single_obs)
        single_num_privileged_obs = 73
        single_linvel_index = 53
        num_privileged_obs = int(c_frame_stack * single_num_privileged_obs)
        num_actions = 12
        num_envs = 4096
        episode_length_s = 24
        use_ref_actions = False
        num_commands = 5             # sin_phase, cos_phase, vx, vy, wz

    class safety:
        pos_limit = 1.0
        vel_limit = 1.0
        torque_limit = 0.85

    class asset(LeggedRobotCfg.asset):
        # asimov_v1_legs.urdf has upper body + toes converted to fixed joints,
        # yielding exactly 12 active DOF (6 per leg) — identical layout to X1.
        file = '{LEGGED_GYM_ROOT_DIR}/resources/robots/asimov_v1/urdf/asimov_v1_legs.urdf'
        # asimov_legs.xml is the same skeleton with 15 non-leg joints stripped,
        # so MuJoCo nq=19 (7 floating base + 12 legs) matches the training URDF.
        # Generated by software/tools/make_legs_mjcf.py.
        xml_file = '{LEGGED_GYM_ROOT_DIR}/../sim-model/xmls/asimov_legs.xml'

        name = "asimov_v1"
        # Substring match against rigid-body names. Asimov uses *_ankle_roll_link and *_knee_link.
        foot_name = "ankle_roll"
        knee_name = "knee"

        # Asimov root link is pelvis_link (X1 uses base_link).
        terminate_after_contacts_on = ['pelvis_link']
        penalize_contacts_on = ['pelvis_link']
        self_collisions = 0          # 0 = enable, 1 = disable
        flip_visual_attachments = False
        replace_cylinder_with_capsule = False
        fix_base_link = False

    class terrain(LeggedRobotCfg.terrain):
        mesh_type = 'trimesh'
        curriculum = False
        measure_heights = False
        static_friction = 0.6
        dynamic_friction = 0.6
        terrain_length = 8.
        terrain_width = 8.
        num_rows = 20
        num_cols = 20
        max_init_terrain_level = 5
        platform = 3.
        terrain_dict = {"flat": 0.3,
                        "rough flat": 0.2,
                        "slope up": 0.2,
                        "slope down": 0.2,
                        "rough slope up": 0.0,
                        "rough slope down": 0.0,
                        "stairs up": 0.,
                        "stairs down": 0.,
                        "discrete": 0.1,
                        "wave": 0.0}
        terrain_proportions = list(terrain_dict.values())

        rough_flat_range = [0.005, 0.01]
        slope_range = [0, 0.1]
        rough_slope_range = [0.005, 0.02]
        stair_width_range = [0.25, 0.25]
        stair_height_range = [0.01, 0.1]
        discrete_height_range = [0.0, 0.01]
        restitution = 0.

    class noise(LeggedRobotCfg.noise):
        add_noise = True
        noise_level = 1.5

        class noise_scales(LeggedRobotCfg.noise.noise_scales):
            dof_pos = 0.02
            dof_vel = 1.5
            ang_vel = 0.2
            lin_vel = 0.1
            quat = 0.1
            gravity = 0.05
            height_measurements = 0.1

    class init_state(LeggedRobotCfg.init_state):
        # Asimov standing height: pelvis_link at 0.63 m (from MJCF default pose).
        # X1 used 0.7 m — Asimov is slightly shorter at the hip.
        pos = [0.0, 0.0, 0.66]

        # Default standing pose: balanced squat with COM over feet.
        # Asimov's pelvis_link origin sits ~5 cm forward of the actual hip
        # joints (an artifact of the MJCF convention — see body_mass diagnostic
        # in tools/test_default_pose.py). Earlier attempts to copy X1's
        # hip_pitch=+0.4 produced a 27 cm forward COM offset because Asimov's
        # +Y hip rotation swings the leg backward, not forward.
        #
        # Configuration here uses the standard "balanced squat" formula:
        #   hip_pitch + ankle_pitch ≈ knee/2 (in magnitude), opposite signs
        # so the shank stays roughly vertical and the foot stays under the hip.
        # Sign of hip_pitch is negative to push the foot forward (because +Y
        # rotation here moves the leg backward), and knee positive to bend
        # toward flexion. Verified with tools/test_default_pose.py.
        default_joint_angles = {
            # COM-centering fix: previous pose (hip_pitch ±0.20) put COM at 28%
            # from heel — leaving only 6.2cm back-margin vs 15.6cm front-margin
            # (foot length 21.8cm including toe). Any forward swing during
            # walking pushed COM past the heel → backward tipping (仰天摔倒).
            # Reduced hip_pitch magnitude from 0.20 to 0.10 to lean torso
            # slightly forward, recentering COM at 50% of foot support polygon.
            # Verified: front-margin 10.9cm, back-margin 10.7cm (balanced).
            'left_hip_pitch_joint':   -0.20,    # was -0.10 — sweep_default_pose: ±0.20 puts COM 1.6cm fwd of ankle mid (±0.10 was 6.1cm)
            'left_hip_roll_joint':    0.10,
            'left_hip_yaw_joint':     0.0,
            'left_knee_joint':        0.40,
            'left_ankle_pitch_joint':-0.20,     # match hip to keep shank vertical
            'left_ankle_roll_joint':  0.0,
            'right_hip_pitch_joint':  0.20,     # mirror
            'right_hip_roll_joint':  -0.10,
            'right_hip_yaw_joint':    0.0,
            'right_knee_joint':      -0.40,
            'right_ankle_pitch_joint': 0.20,    # mirror
            'right_ankle_roll_joint': 0.0,
        }

    class control(LeggedRobotCfg.control):
        control_type = 'P'

        # PD gains.
        # Note: hip_pitch was kp=30 (X1 baseline) but test_lift_foot.py showed
        # hip_pitch could not pull the leg into a -0.6 target — only reached
        # -0.31 (50% tracking error). The required torque to lift a 6.4 kg leg
        # with COM at 0.25m is ~16 N·m; kp=30 with realistic error of 0.2 only
        # provides 6 N·m. Doubled to kp=60 so hip_pitch can actually pull the
        # leg forward against gravity.
        stiffness = {
            'hip_pitch_joint':   100,    # X1: 30 -> 100 (3.3x): test_lift_foot showed kp=30 only achieved 50% target tracking
            'hip_roll_joint':    40,     # X1: 40 (kept) — too high kp makes lateral lean unstable
            'hip_yaw_joint':     35,
            'knee_joint':        200,    # X1: 100 -> 200 (2x): need to support full body weight during single-foot phase
            'ankle_pitch_joint': 50,     # X1: 35 -> 50: ankle strategy stability
            'ankle_roll_joint':  40,     # X1: 35 -> 40: foot-roll stability during single-foot
        }
        damping = {
            'hip_pitch_joint':   8,      # scale with kp
            'hip_roll_joint':    3.0,    # X1 baseline
            'hip_yaw_joint':     4,
            'knee_joint':        15,
            'ankle_pitch_joint': 1.0,
            'ankle_roll_joint':  3.0,
        }

        action_scale = 0.5
        decimation = 10   # sim @ 1000 Hz, policy @ 100 Hz

    class sim(LeggedRobotCfg.sim):
        dt = 0.001
        substeps = 1
        up_axis = 1

        class physx(LeggedRobotCfg.sim.physx):
            num_threads = 10
            solver_type = 1
            num_position_iterations = 4
            num_velocity_iterations = 0
            contact_offset = 0.01
            rest_offset = 0.0
            bounce_threshold_velocity = 0.5
            max_depenetration_velocity = 1.0
            max_gpu_contact_pairs = 2**23
            default_buffer_size_multiplier = 5
            contact_collection = 2

    class domain_rand(LeggedRobotCfg.domain_rand):
        randomize_friction = True
        friction_range = [0.2, 1.3]
        restitution_range = [0.0, 0.4]

        push_robots = True
        push_interval_s = 4
        update_step = 2000 * 24
        push_duration = [0, 0.05, 0.1, 0.15, 0.2, 0.25]
        max_push_vel_xy = 0.2
        max_push_ang_vel = 0.2

        randomize_base_mass = True
        added_mass_range = [-3, 3]

        randomize_com = True
        com_displacement_range = [[-0.05, 0.05],
                                  [-0.05, 0.05],
                                  [-0.05, 0.05]]

        randomize_gains = True
        stiffness_multiplier_range = [0.8, 1.2]
        damping_multiplier_range = [0.8, 1.2]

        randomize_torque = True
        torque_multiplier_range = [0.8, 1.2]

        randomize_link_mass = True
        added_link_mass_range = [0.9, 1.1]

        randomize_motor_offset = True
        motor_offset_range = [-0.035, 0.035]

        randomize_joint_friction = True
        randomize_joint_friction_each_joint = False
        joint_friction_range = [0.01, 1.15]
        joint_1_friction_range = [0.01, 1.15]
        joint_2_friction_range = [0.01, 1.15]
        joint_3_friction_range = [0.01, 1.15]
        joint_4_friction_range = [0.5, 1.3]
        joint_5_friction_range = [0.5, 1.3]
        joint_6_friction_range = [0.01, 1.15]
        joint_7_friction_range = [0.01, 1.15]
        joint_8_friction_range = [0.01, 1.15]
        joint_9_friction_range = [0.5, 1.3]
        joint_10_friction_range = [0.5, 1.3]

        randomize_joint_damping = True
        randomize_joint_damping_each_joint = False
        joint_damping_range = [0.3, 1.5]
        joint_1_damping_range = [0.3, 1.5]
        joint_2_damping_range = [0.3, 1.5]
        joint_3_damping_range = [0.3, 1.5]
        joint_4_damping_range = [0.9, 1.5]
        joint_5_damping_range = [0.9, 1.5]
        joint_6_damping_range = [0.3, 1.5]
        joint_7_damping_range = [0.3, 1.5]
        joint_8_damping_range = [0.3, 1.5]
        joint_9_damping_range = [0.9, 1.5]
        joint_10_damping_range = [0.9, 1.5]

        randomize_joint_armature = True
        randomize_joint_armature_each_joint = False
        joint_armature_range = [0.0001, 0.05]
        joint_1_armature_range = [0.0001, 0.05]
        joint_2_armature_range = [0.0001, 0.05]
        joint_3_armature_range = [0.0001, 0.05]
        joint_4_armature_range = [0.0001, 0.05]
        joint_5_armature_range = [0.0001, 0.05]
        joint_6_armature_range = [0.0001, 0.05]
        joint_7_armature_range = [0.0001, 0.05]
        joint_8_armature_range = [0.0001, 0.05]
        joint_9_armature_range = [0.0001, 0.05]
        joint_10_armature_range = [0.0001, 0.05]

        add_lag = True
        randomize_lag_timesteps = True
        randomize_lag_timesteps_perstep = False
        lag_timesteps_range = [5, 40]

        add_dof_lag = True
        randomize_dof_lag_timesteps = True
        randomize_dof_lag_timesteps_perstep = False
        dof_lag_timesteps_range = [0, 40]

        add_dof_pos_vel_lag = False
        randomize_dof_pos_lag_timesteps = False
        randomize_dof_pos_lag_timesteps_perstep = False
        dof_pos_lag_timesteps_range = [7, 25]
        randomize_dof_vel_lag_timesteps = False
        randomize_dof_vel_lag_timesteps_perstep = False
        dof_vel_lag_timesteps_range = [7, 25]

        add_imu_lag = False
        randomize_imu_lag_timesteps = True
        randomize_imu_lag_timesteps_perstep = False
        imu_lag_timesteps_range = [1, 10]

        randomize_coulomb_friction = True
        joint_coulomb_range = [0.1, 0.9]
        joint_viscous_range = [0.05, 0.1]

    class commands(LeggedRobotCfg.commands):
        curriculum = True
        max_curriculum = 1.5
        num_commands = 4
        resampling_time = 25.
        gait = ["walk_omnidirectional", "stand", "walk_omnidirectional"]
        gait_time_range = {"walk_sagittal": [2, 6],
                           "walk_lateral": [2, 6],
                           "rotate": [2, 3],
                           "stand": [2, 3],
                           "walk_omnidirectional": [4, 6]}
        heading_command = False
        stand_com_threshold = 0.05
        sw_switch = True

        class ranges:
            lin_vel_x = [-0.4, 1.2]
            lin_vel_y = [-0.4, 0.4]
            ang_vel_yaw = [-0.6, 0.6]
            heading = [-3.14, 3.14]

    class rewards:
        soft_dof_pos_limit = 0.98
        soft_dof_vel_limit = 0.9
        soft_torque_limit = 0.9
        # Asimov pelvis_link sits at 0.63 m at default pose, but with the
        # default-bent-knee init posture above, expected standing height is
        # roughly 0.58 m. Tune empirically once training runs.
        base_height_target = 0.58
        foot_min_dist = 0.15         # Asimov hip width ~0.135 m (vs X1 0.2)
        foot_max_dist = 1.0

        # Swing-leg reference offsets (added to default_dof_pos during swing).
        # Asimov has LEFT/RIGHT mirrored joint axes (hip_pitch, knee,
        # ankle_pitch), unlike X1 where left and right share the same axis
        # sign. The original X1 values pushed both knees in the +q direction
        # for flexion, but Asimov's right knee flexes in the -q direction
        # (range [-1.5, 0]), so the X1 numbers drove the right knee command
        # against its limit — confirmed in sim2sim where right knee q stuck
        # at 0 with tau saturated.
        #
        # Order: [left:  hip_pitch, hip_roll, hip_yaw, knee, ankle_pitch, ankle_roll,
        #         right: hip_pitch, hip_roll, hip_yaw, knee, ankle_pitch, ankle_roll]
        # Magnitudes reduced from X1's 0.35 (knee) to 0.20, matching the smaller
        # default knee bend Asimov uses (0.40 vs X1's 0.49).
        final_swing_joint_delta_pos = [
            -0.10,  0.05, 0.0,  0.20, -0.10, 0.0,   # left  (forward swing)
            +0.10, -0.05, 0.0, -0.20, +0.10, 0.0,   # right (mirrored axes)
        ]
        target_feet_height = 0.03
        target_feet_height_max = 0.06
        feet_to_ankle_distance = 0.041
        cycle_time = 0.7
        only_positive_rewards = True
        tracking_sigma = 5
        max_contact_force = 700

        class scales:
            # Identical to X1's scales — X1 trains stable walking with these.
            # Earlier attempts to scale up feet_air_time/feet_clearance were
            # treating symptoms; the actual problem (right ankle_pitch sign,
            # mirrored joint axes) is now fixed in default_joint_angles and
            # final_swing_joint_delta_pos. Reverting reward scales to X1
            # baseline to test whether the fixes alone are sufficient.
            ref_joint_pos = 2.2
            feet_clearance = 1.
            feet_contact_number = 2.0
            feet_air_time = 1.2
            foot_slip = -0.1
            feet_distance = 0.2
            knee_distance = 0.2
            feet_contact_forces = -0.01
            tracking_lin_vel = 1.8        # v12 boosted to 5.0 but plateaued — reverted to v11 baseline
            tracking_ang_vel = 1.1        # v12: 2.5, reverted
            vel_mismatch_exp = 0.5
            low_speed = 0.2
            track_vel_hard = 0.5          # v12: 1.5, reverted
            default_joint_pos = 1.0       # v12 gated to stand-only, reverted — this regularizer was needed
            orientation = 1.
            feet_rotation = 0.3
            base_height = 0.2
            base_acc = 0.2
            action_smoothness = -0.002
            torques = -8e-9
            dof_vel = -2e-8
            dof_acc = -1e-7
            collision = -1.
            stand_still = 2.5
            dof_vel_limits = -1
            dof_pos_limits = -10.
            dof_torque_limits = -0.1
            # Dense reward for foot lift during walking commands. Required
            # because feet_air_time (sparse, only on landing) and feet_clearance
            # (gated by gait swing_mask) are too weak as exploration signals.
            # v11 used 10.0 and successfully escaped the "fake gait" attractor.
            # v12 dropped to 3.0; combined with other changes, training plateaued
            # worse than v11. Reverted to 10.0.
            feet_height_walking = 10.0

    class normalization:
        class obs_scales:
            lin_vel = 2.
            ang_vel = 1.
            dof_pos = 1.
            dof_vel = 0.05
            quat = 1.
            height_measurements = 5.0
        clip_observations = 100.
        clip_actions = 100.


class AsimovStandCfgPPO(LeggedRobotCfgPPO):
    seed = 5
    runner_class_name = 'DHOnPolicyRunner'

    class policy:
        init_noise_std = 1.0
        actor_hidden_dims = [512, 256, 128]
        critic_hidden_dims = [768, 256, 128]
        state_estimator_hidden_dims = [256, 128, 64]
        kernel_size = [6, 4]
        filter_size = [32, 16]
        stride_size = [3, 2]
        lh_output_dim = 64
        in_channels = AsimovStandCfg.env.frame_stack

    class algorithm(LeggedRobotCfgPPO.algorithm):
        entropy_coef = 0.001
        learning_rate = 1e-5
        num_learning_epochs = 2
        gamma = 0.994
        lam = 0.9
        num_mini_batches = 4
        if AsimovStandCfg.terrain.measure_heights:
            lin_vel_idx = (AsimovStandCfg.env.single_num_privileged_obs + AsimovStandCfg.terrain.num_height) * (AsimovStandCfg.env.c_frame_stack - 1) + AsimovStandCfg.env.single_linvel_index
        else:
            lin_vel_idx = AsimovStandCfg.env.single_num_privileged_obs * (AsimovStandCfg.env.c_frame_stack - 1) + AsimovStandCfg.env.single_linvel_index

    class runner:
        policy_class_name = 'ActorCriticDH'
        algorithm_class_name = 'DHPPO'
        num_steps_per_env = 24
        max_iterations = 20000
        save_interval = 100
        experiment_name = 'asimov_stand'
        run_name = ''
        resume = False
        load_run = -1
        checkpoint = -1
        resume_path = None
